apiVersion: apps/v1
kind: Deployment
metadata:
  name:"aaa"
  labels:
    app: "abb"
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - abb

  template:
    spec:
      containers:
        - name: nginx


