apiVersion: rbac.authorization.k8s.io/v1
kind: Plu
metadata:
  name:
  labels:
    app:
spec:
  containers:
    - name:
      image:
      imagePullPolicy: IfNotPresent
  restartPolicy: Always

eventTime:
